# Code generated from a VideoML scrip
# Video name: fragmovie

from moviepy import *

font = "./font/font.ttf"

video_width = 640
video_height = 360

final_clip_list = []
warning = TextClip(text="Attention au volume", font=font, font_size=48, color='white').with_start(0).with_duration(5)
warning = warning.with_position(('center', 'center'))
final_clip_list.append(warning)
intro = VideoFileClip("intro.mp4")
intro = intro.with_start(warning.end)
intro = intro.with_position(('center', 'center'))
final_clip_list.append(intro)
intro_text = TextClip(text="Fragmovie", font=font, font_size=48, color='white').with_start(intro.start + 2).with_duration(8)
intro_text = intro_text.with_position(('center', 'center'))
intro_text = intro_text.with_effects([vfx.CrossFadeIn(2.0)])
final_clip_list.append(intro_text)
intro_text_creator = TextClip(text="Created by PADD", font=font, font_size=48, color='white').with_start(intro.start + 5).with_duration(5)
intro_text_creator = intro_text_creator.with_position(('center', 'bottom'))
intro_text_creator = intro_text_creator.with_effects([vfx.CrossFadeIn(2.0)])
final_clip_list.append(intro_text_creator)
explosion_left = VideoFileClip("explosion.mp4").subclipped(0, 3)
explosion_left = explosion_left.with_effects([vfx.MaskColor(color=(0, 255, 8), threshold=150, stiffness=5)])
explosion_left = explosion_left.resized(0.3)
explosion_left = explosion_left.with_start(intro.start + 5)
explosion_left = explosion_left.with_position(('left', 'bottom'))
final_clip_list.append(explosion_left)
explosion_right = VideoFileClip("explosion.mp4").subclipped(0, 3)
explosion_right = explosion_right.with_effects([vfx.MaskColor(color=(0, 255, 8), threshold=150, stiffness=5)])
explosion_right = explosion_right.resized(0.3)
explosion_right = explosion_right.with_start(intro.start + 5)
explosion_right = explosion_right.with_position(('right', 'bottom'))
final_clip_list.append(explosion_right)
zywoo_gameplay = VideoFileClip("gameplay.mp4").subclipped(5, 18)
zywoo_gameplay = zywoo_gameplay.with_effects([vfx.FadeIn(2.0)])
zywoo_gameplay = zywoo_gameplay.with_effects([vfx.Freeze(12, 2)])
zywoo_gameplay = zywoo_gameplay.with_start(intro.end)
zywoo_gameplay = zywoo_gameplay.with_position(('center', 'center'))
final_clip_list.append(zywoo_gameplay)
therock_ok1 = VideoFileClip("therock.mp4").subclipped(0, 3)
therock_ok1 = therock_ok1.with_effects([vfx.MaskColor(color=(0, 255, 8), threshold=100, stiffness=5)])
therock_ok1 = therock_ok1.resized(0.4)
therock_ok1 = therock_ok1.with_start(zywoo_gameplay.start + 2)
therock_ok1 = therock_ok1.with_position(('right', 'bottom'))
final_clip_list.append(therock_ok1)
therock_ok2 = VideoFileClip("therock.mp4").subclipped(0, 3)
therock_ok2 = therock_ok2.with_effects([vfx.MaskColor(color=(0, 255, 8), threshold=100, stiffness=5)])
therock_ok2 = therock_ok2.resized(0.4)
therock_ok2 = therock_ok2.with_start(zywoo_gameplay.start + 7)
therock_ok2 = therock_ok2.with_position(('left', 'bottom'))
final_clip_list.append(therock_ok2)
therock_nok = VideoFileClip("therock.mp4").subclipped(3, 4)
therock_nok = therock_nok.with_effects([vfx.MaskColor(color=(0, 255, 8), threshold=100, stiffness=5)])
therock_nok = therock_nok.resized(0.4)
therock_nok = therock_nok.with_start(zywoo_gameplay.start + 12)
therock_nok = therock_nok.with_position(('center', 'bottom'))
final_clip_list.append(therock_nok)
monesy_gameplay = VideoFileClip("gameplay.mp4").subclipped(37, 48)
monesy_gameplay = monesy_gameplay.with_start(zywoo_gameplay.end)
monesy_gameplay = monesy_gameplay.with_position(('center', 'center'))
AUTO_GENERATED_CLIP_0 = AudioFileClip("background.mp3").subclipped(25, 36).with_start(monesy_gameplay.start+0).with_end(monesy_gameplay.start+11).with_effects([afx.MultiplyVolume(1.0)])
monesy_gameplay = monesy_gameplay.with_audio(AUTO_GENERATED_CLIP_0)
final_clip_list.append(monesy_gameplay)
ohmygod = VideoFileClip("ohmygod.mp4")
ohmygod = ohmygod.with_effects([vfx.MaskColor(color=(0, 255, 8), threshold=150, stiffness=5)])
ohmygod = ohmygod.resized(1.0)
ohmygod = ohmygod.with_start(monesy_gameplay.start + 2)
ohmygod = ohmygod.with_position(('center', 'bottom'))
final_clip_list.append(ohmygod)
shocked = ImageClip("shocked.png").with_start(monesy_gameplay.start + 5).with_duration(monesy_gameplay.end - monesy_gameplay.start - 5)
shocked = shocked.with_position(('right', 'top'))
shocked = shocked.resized(0.5)
final_clip_list.append(shocked)
hop_on_rigole = TextClip(text="Hop on rigole", font=font, font_size=48, color='white').with_start(monesy_gameplay.end).with_duration(5)
hop_on_rigole = hop_on_rigole.with_position(('center', 'center'))
hop_on_rigole = hop_on_rigole.with_effects([vfx.CrossFadeIn(2.0)])
hop_on_rigole = hop_on_rigole.with_effects([vfx.CrossFadeOut(2.0)])
final_clip_list.append(hop_on_rigole)
hrek = VideoFileClip("shrek.mp4")
hrek = hrek.with_effects([vfx.FadeIn(2.0)])
hrek = hrek.with_effects([vfx.MultiplySpeed(2.5)])
hrek = hrek.resized(width=640, height=360)
hrek = hrek.with_start(hop_on_rigole.end)
hrek = hrek.with_position(('center', 'center'))
AUTO_GENERATED_CLIP_1 = AudioFileClip("formula.mp3").subclipped(0, hrek.end).with_start(hrek.start).with_end(hrek.end).with_effects([afx.MultiplyVolume(2.0)])
hrek = hrek.with_audio(AUTO_GENERATED_CLIP_1)
final_clip_list.append(hrek)
outro_text = TextClip(text="The End", font=font, font_size=48, color='white').with_start(hrek.end).with_duration(5)
outro_text = outro_text.with_position(('center', 'center'))
outro_text = outro_text.with_effects([vfx.CrossFadeIn(2.0)])
final_clip_list.append(outro_text)
final_clip = CompositeVideoClip(final_clip_list, size=(video_width, video_height))
final_clip.write_videofile("fragmovie.mp4", codec="libx264", fps=24)
